travis:
  secure:
    BINSTAR_TOKEN: HK4U9qHuCDzVs34BLRmdReLKaZjs6D47mweo2zr28FELDQn+K5k+bqU9YpaF5s/oDlQWM4lvFDyNtmEerdJtcZnqJpnqkc8s3omlSddtSuW+Q2PWPolz3x6l4y6GCYT2cZPwPYqhPThJ6l3C7q0zqwwUEJdGgw08We24bgqWTlwZGUKduE833I/fu5XlCrF9T4J8Zu2AVZPzv9J++QrZrxvRr38vSyQ1KYV+NB8th3q+GYTEMbmvWLX5y6ItEG+10mE9oA6/rtvY9n1JAmb6iOriK3uJBdO8E2TdTfVsVL6FivzFIM7X1xT8nfxAYveKtuudAIPtlzsKSBxQTcV/7aqEVfjrhoDvXqYJtrs/KIOrXaU6xaqUU3cZSrUn5jje1Fl2kx6R2srXqrIIg2TNHXahtRR8//WsSATSBRYKldLFS/4zEb5Ha4R19o/CIptdrA/UvoB1RtfBx4qe2AevuzJkvNiHIg4sm48cl7x+O/tuvs9cqLlb1JOhZHa1mgUnywxmNNwXcE63EUATpODu5tquTJSa5GRcsrT3FGnP2e4fwk204VKHjdS4Pd0SHr9u3Bh1SiozNJTrw1oIFdagwB2RSCR2JQnlMviSonlbQtle8FwRRJ4b8w3jXgjLaCai9uf7pNRJJa4Xvlht2Oj+sTmPSjcSK+CNC5i/FszFCYU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
